### ISSUE TITLE
Unable to load jnetpcap library from java.library.path

### ISSUE THREAD

**Issue by philross88** [nccgroup/pcap-burp#7]
I am getting the above error on all platforms. I have added JnetPcap in java library but still getting the same error message. Not sure what's wrong. 
On Windows I have following steps done:
1- WinPcap Installed
2- jnetpcap library path set in burp and Java.library.path
3- imported burp-pcap from bAppstore.

Please advise.

Thanks

**Comment by MarioVilas** [comment]
Same here. The pre-built JnetPcap library appears to have been dynamically linked against libpcap, I have no idea which version, and it will not link against the one in my system (Fedora 25). I'm going to try compiling JnetPcap myself.

Libpcap should have been compiled statically to prevent this, I think.

EDIT: I ended up just grabbing the JnetPcap binaries for Red Hat from their website and creating a symbolic link to the version of libpcap they expected (0.9.4). This solved the linking problem, but the plugin still won't work - I'm kinda stumped now, since building from sources won't work on my machine either, and I simply don't have the time right now to figure out why. &lt;rant&gt; This kinda crap is exactly why I always hated Java &lt;/rant&gt;

**Comment by neonbunny** [comment]
As a result of your problems I have switched to using a pure Java implementation of a Pcap parser, which removes the need for the additional native binaries.
